config/routes.rb
Rails.application.routes.draw do
  resources :flight_routes do
    resources :flights do
      member do
        patch :mark_as_arrived
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :flight_route

  def name
    "#{airline.to_s.upcase} #{flight_number}"
  end

  def mark_as_arrived!
    return if arrived_at
    FlightMailer.arrive(self, "russell@theironyard.com").deliver_now
    self.arrived_at = Time.zone.now
    save
  end
end

app/models/flight_route.rb
class FlightRoute < ApplicationRecord
  has_many :flights
  validates :origin, presence: true, length: { in: 3..4 }
  validates :destination, presence: true, length: { in: 3..4 }
  # validates :food, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flight_routes_controller.rb
class FlightRoutesController < ApplicationController
  before_action :set_flight_route, only: [:show, :edit, :update, :destroy]

  # GET /flight_routes
  def index
    @flight_routes = FlightRoute.all
  end

  # GET /flight_routes/1
  def show
  end

  # GET /flight_routes/new
  def new
    @flight_route = FlightRoute.new
  end

  # GET /flight_routes/1/edit
  def edit
  end

  # POST /flight_routes
  def create
    @flight_route = FlightRoute.new(flight_route_params)

    if @flight_route.save
      redirect_to @flight_route, notice: 'Flight route was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flight_routes/1
  def update
    if @flight_route.update(flight_route_params)
      redirect_to @flight_route, notice: 'Flight route was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flight_routes/1
  def destroy
    @flight_route.destroy
    redirect_to flight_routes_url, notice: 'Flight route was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight_route
      @flight_route = FlightRoute.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flight_route_params
      params.require(:flight_route).permit(:origin, :destination, :food)
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight_route = FlightRoute.find(params[:flight_route_id])
    @flights = @flight_route.flights
  end

  def new
    @flight_route = FlightRoute.find(params[:flight_route_id])
    @flight = @flight_route.flights.build
  end

  def create
    @flight_route = FlightRoute.find(params[:flight_route_id])
    @flight = @flight_route.flights.build(flight_params)

    if @flight.save
      redirect_to flight_routes_path, notice: "Flight Created!"
    else
      render "new"
    end
  end

  def edit
  end

  def mark_as_arrived
    @flight = Flight.find(params[:id])
    @flight.mark_as_arrived!

    redirect_to flight_route_flights_path(@flight.flight_route)
  end

  private def flight_params
    params.require(:flight).permit(
      :flight_number,
      :airline,
      :number_of_passengers,
      :arrived_at,
      :stocked_at,
      :cleaned_at,
      :gate
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flight_routes_helper.rb
module FlightRoutesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flight_routes/_form.html.erb
<%= form_for(flight_route) do |f| %>
  <% if flight_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight_route.errors.count, "error") %> prohibited this flight route from being saved:</h2>

      <ul>
      <% flight_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :destination %>
    <%= f.text_field :destination %>
  </div>

  <div class="field">
    <%= f.label :food %>
    <%= f.check_box :food %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flight_routes/edit.html.erb
<h1>Editing Flight Route</h1>

<%= render 'form', flight_route: @flight_route %>

<%= link_to 'Show', @flight_route %> |
<%= link_to 'Back', flight_routes_path %>

app/views/flight_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flight Routes</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>Food</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @flight_routes.each do |flight_route| %>
      <tr>
        <td><%= flight_route.origin %></td>
        <td><%= flight_route.destination %></td>
        <td><%= flight_route.food %></td>
        <td><%= link_to 'Show', flight_route %></td>
        <td><%= link_to 'New Flight', new_flight_route_flight_path(flight_route) %></td>
        <td><%= link_to 'Edit', edit_flight_route_path(flight_route) %></td>
        <td><%= link_to 'Destroy', flight_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight Route', new_flight_route_path %>

app/views/flight_routes/new.html.erb
<h1>New Flight Route</h1>

<%= render 'form', flight_route: @flight_route %>

<%= link_to 'Back', flight_routes_path %>

app/views/flight_routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @flight_route.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight_route.destination %>
</p>

<p>
  <strong>Food:</strong>
  <%= @flight_route.food %>
</p>

<%= link_to 'Edit', edit_flight_route_path(@flight_route) %> |
<%= link_to 'Back', flight_routes_path %>

app/views/flights/edit.html.erb
<h1>Flights#edit</h1>
<p>Find me in app/views/flights/edit.html.erb</p>

app/views/flights/index.html.erb
<h1>Flights for <%= @flight_route.origin %> to <%= @flight_route.destination %></h1>
<ul>
  <% @flights.each do |flight| %>
    <li>
      <%= flight.name %>

      <% if flight.arrived_at %>
        Arrived
        <%= time_ago_in_words(flight.arrived_at) %>
        ago
      <% else %>
        <%= link_to("Arrived!", mark_as_arrived_flight_route_flight_path(@flight_route, flight), method: :patch) %>
      <% end %>


    </li>
  <% end %>
</ul>

app/views/flights/new.html.erb
<%= form_for [@flight_route, @flight] do |f| %>
  <fieldset class="field">
    <%= f.label "flight_number" %>
    <%= f.text_field   "flight_number" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "airline" %>
    <%= f.text_field   "airline" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "number_of_passengers" %>
    <%= f.number_field  "number_of_passengers" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "arrived_at" %>
    <%= f.datetime_field "arrived_at" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "stocked_at" %>
    <%= f.datetime_field "stocked_at" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "cleaned_at" %>
    <%= f.datetime_field "cleaned_at" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "gate" %>
    <%= f.text_field   "gate" %>
  </fieldset>
  <fieldset class="field">
    <%= f.label "flight_route_id" %>
    <%= f.number_field  "flight_route_id" %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>